import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/Header";
import SideNav from "@/components/SideNav";
import { Separator } from "@/components/ui/separator"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
           <div className="flex flex-col w-full h-full min-h-screen py-5 px-7">
            <Header />
            <div className="flex flex-row w-full mt-11">
              <SideNav />
              <Separator orientation="vertical" className=" h-screen mr-6" />
            {children}
            </div>
           </div>
          </ThemeProvider></body>
    </html>
  );
}
